baseURL = "https://www.braveheart.xyz"
title = "braveheat.xyz"
author = "Seth Huang"
paginate = 20
languageCode = "zh"
DefaultContentLanguage = "zh"
enableInlineShortcodes = true

theme="plain"

enableEmoji= true
enableRobotsTXT= true

# Syntax Highlight Options
pygmentsCodeFencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "vs"
[pygmentsOptions]
  linenos= true

[markup]
  defaultMarkdownHandler= "goldmark"